#!/usr/bin/env python3

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fibblenacho(max=max):
    thing = [1, 2, 3]
    i = len(thing) - 1
    while thing[i] < 4000000:
        thing.append(thing[i] + thing[i - 1])
        i += 1
    return thing[0:i]


def nachoEven(urmom):
    for x in urmom[:]:
        if x % 2 != 0:
            urmom.remove(x)
    return urmom


print(sum(nachoEven(fibblenacho(max=4000000))))
